<div id="import">
	<h1>Инициализация...</h1>

	<div class="progress">
		<div class="progress-description hidden">
			<span class="progress-description__item progress-description__item--done">0</span>
			<span class="progress-description__item progress-description__item--of">из</span>
			<span class="progress-description__item progress-description__item--total">0</span>
			<span class="progress-description__item progress-description__item--percentage">(0.0%)</span>
		</div>

		<div class="progress__bar" style="width: 0"></div>
	</div>

	<div class="message hidden">
		<h2 class="message__title"></h2>
		<div class="message__text"></div>
	</div>

	<div class="actions">
		<button name="pause" disabled>Запуск...</button>
	</div>

	<div class="errors hidden">
		<h2>Ошибки</h2>

		<div class="error-list">
		</div>
	</div>
</div>

<script type="text/javascript">
	window.FrontendData = <?=json_encode(['queueId' => $this->queue_id])?>;
</script>

<!--suppress JSUnresolvedLibraryURL -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
<script src="/assets/import/import.js" type="text/javascript"></script>